### ISSUE TITLE
GitHub上でLaTeX数式が正しく表示されない

### ISSUE THREAD

**Issue by kitsuyaazuma** [tomomiyazaki/exercises#1]
ローカルのマークダウンビューアーでは問題ありませんが、GitHub上ではLaTex数式が正しく表示されていない箇所がありました。

[image_processing/5_color_system.md](https://github.com/tomomiyazaki/exercises/blob/master/image_processing/5_color_system.md)について、以下のように修正することで数式が正しく表示されることを確認しました。

```diff md
#### 変換式
$$
- \left ( \begin{array}{lll} y\\ I\\ Q \end{array} \right)
-  =
+ \left ( \begin{array}{lll} y\\ I\\ Q \end{array} \right) =
 \left ( \begin{array}{lll}
 0.299 &0.587 &0.114\\
 0.596 &-0.274 &-0.322\\
 0.211 &-0.523 &0.312
 \end{array} \right)
 \left ( \begin{array}{lll} R\\ G\\ B \end{array} \right)
$$


$$
- \left ( \begin{array}{lll} R\\ G\\ B \end{array} \right)
- =
+ \left ( \begin{array}{lll} R\\ G\\ B \end{array} \right) =
 \left ( \begin{array}{lll}
 1 &0.956 &0.621\\
 1 &-0.273 &-0.647\\
 1 &-1.104 &1.70
 \end{array} \right)
 \left ( \begin{array}{lll} Y\\ I\\ Q \end{array} \right)
$$
```

原因は、行頭の`=`がヘッダーとして解釈されたためだと考えられます。

[Basic Syntax \| Markdown Guide](https://www.markdownguide.org/basic-syntax/#alternate-syntax)

これから取り組む学生が見やすくなると思うので、お手隙の際に修正をよろしくお願いいたします。

**Comment by tomomiyazaki** [comment]
どうもありがとう！修正しておきました！
